version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '@b86aH123456'
    ports:
      - "3306:3306"
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://medicalapp.mysql.database.azure.com/medicalapp
      - SPRING_DATASOURCE_USERNAME=MedAppAdmin
      - SPRING_DATASOURCE_PASSWORD=@b86aH123456
