spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/

        - id: discovery-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/hours,
              /auth/**,
              /api/doctors/**,
              /api/doctor-detail/**,
              /api/rating/**,
              /api/departments/**,
              /api/appointment/**,
              /api/user/**,
              /api/scrape/**,
              /api/medicine/**,
              /api/medicine-unit/**,
              /api/medication-schedule/**,
              /api/schedule-time/**,
              /api/schedule-time-detail/**,
              /api/post,
              /api/post/**,
              /api/category,
              /api/weight,
              /api/weight/**,
              /api/fee/**,
          filters:
            - AuthenticationFilter


        - id: websocket-service
          uri: lb://websocket-service
          predicates:
            - Path=/ws/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**,
              /api/user-device/**

        - id: vnpay-service
          uri: lb://vnpay-service
          predicates:
            - Path=/api/payment/**

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**,
              /api/auth/validate,
              /login-google/auth-google/**,

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
