eureka-server: http://localhost:8761

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: discovery-service
          uri: ${eureka-server}
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/

        - id: discovery-service-static
          uri: ${eureka-server}
          predicates:
            - Path=/eureka/**

        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core-service/v3/api-docs,
              /api/hours,
              /auth/**,
              /api/doctors/**,
              /api/doctor-detail/**,
              /api/rating/**,
              /api/departments/**,
              /api/appointment/**,
              /api/user/**,
              /api/scrape/**,
              /api/post,
              /api/post/**,
              /api/category,
              /api/weight,
              /api/weight/**,
              /api/fee/**,
              /api/user-post,
              /api/user-post/**,
              /api/stats/**,
          filters:
            - AuthenticationFilter


        - id: websocket-service
          uri: lb://websocket-service
          predicates:
            - Path=/websocket-service/v3/api-docs,
              /ws/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/v3/api-docs,
              /api/notification/**,
              /api/user-device/**

        - id: medication-service
          uri: lb://medication-service
          predicates:
            - Path=/medication-service/v3/api-docs,
              /api/medicine/**,
              /api/medicine-unit/**,
              /api/medication-schedule/**,
              /api/schedule-time/**,
              /api/schedule-time-detail/**,
              /api/medication-schedule-group/**

        - id: vnpay-service
          uri: lb://vnpay-service
          predicates:
            - Path=/vnpay-service/v3/api-docs,
              /api/payment/**

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication-service/v3/api-docs,
              /api/auth/**,
              /api/auth/validate,
              /login-google/auth-google/**,
              /api/otp/**,

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /authentication-service/v3/api-docs
        name: Authentication Service
      - url: /core-service/v3/api-docs
        name: Core Service
      - url: /notification-service/v3/api-docs
        name: Notification Service
      - url: /medication-service/v3/api-docs
        name: Medication Service
      - url: /vnpay-service/v3/api-docs
        name: Payment Service
      - url: /v3/api-docs
        name: API Gateway Service
#      - url: /websocket-service/v3/api-docs
#        name: Websocket Service


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
