name: Project CI CD flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Login to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Define an array of service names
    env:
      SERVICES: "discovery-service gateway-service core-service notification-service websocket-service authentication-service vnpay-service medication-service"

    # Iterate over each service and build & push Docker image
    - name: Build & push Docker images
      run: |
        for service in $SERVICES; do
          echo "Building & pushing Docker image for $service"
          docker/build-push-action@v2 --context ./$service --image le132/$service --tags latest
        done
