name: Project CI CD flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image for Discovery Service
      uses: docker/build-push-action@v2
      with:
        context: ./discovery-service
        push: true
        tags: latest

    - name: Build & push Docker image for Gateway Service
      uses: docker/build-push-action@v2
      with:
        context: ./gateway-service
        push: true
        tags: latest

    - name: Build & push Docker image for Core Service
      uses: docker/build-push-action@v2
      with:
        context: ./core-service
        push: true
        tags: latest

    - name: Build & push Docker image for Notification Service
      uses: docker/build-push-action@v2
      with:
        context: ./notification-service
        push: true
        tags: latest

    - name: Build & push Docker image for Websocket Service
      uses: docker/build-push-action@v2
      with:
        context: ./websocket-service
        push: true
        tags: latest

    - name: Build & push Docker image for VnPay Service
      uses: docker/build-push-action@v2
      with:
        context: ./vnpay-service
        push: true
        tags: latest

    - name: Build & push Docker image for Medication Service
      uses: docker/build-push-action@v2
      with:
        context: ./medication-service
        push: true
        tags: latest
